-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 18:30:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seeding
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seeding` ;

-- -----------------------------------------------------
-- Schema seeding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seeding` DEFAULT CHARACTER SET utf8 ;
USE `seeding` ;

-- -----------------------------------------------------
-- Table `seeding`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seeding`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `VIN` VARCHAR(30) NOT NULL,
  `Manufacturer` VARCHAR(20) NOT NULL,
  `Model` VARCHAR(20) NULL,
  `Year_fabrication` YEAR NULL,
  `Color` VARCHAR(10) NULL,
  PRIMARY KEY (`VIN`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `VIN_UNIQUE` (`VIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seeding`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seeding`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(20) NULL,
  `Email` VARCHAR(20) NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(20) NULL,
  `Province` VARCHAR(20) NULL,
  `Country` VARCHAR(20) NULL,
  `Postal_code` INT NULL,
  PRIMARY KEY (`Customer_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Customer_ID_UNIQUE` (`Customer_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seeding`.`Salespersons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seeding`.`Salespersons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Staff_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Store` VARCHAR(20) NULL,
  PRIMARY KEY (`Staff_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Staff_ID_UNIQUE` (`Staff_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seeding`.`Invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seeding`.`Invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Log` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `S_Staff_ID` INT NOT NULL,
  `C_VIN` VARCHAR(30) NOT NULL,
  `C_Customer_ID` INT NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Invoices_Salespersons_idx` (`S_Staff_ID` ASC) VISIBLE,
  INDEX `fk_Invoices_Cars1_idx` (`C_VIN` ASC) VISIBLE,
  INDEX `fk_Invoices_Customers1_idx` (`C_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Invoices_Salespersons`
    FOREIGN KEY (`S_Staff_ID`)
    REFERENCES `seeding`.`Salespersons` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Cars1`
    FOREIGN KEY (`C_VIN`)
    REFERENCES `seeding`.`Cars` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Customers1`
    FOREIGN KEY (`C_Customer_ID`)
    REFERENCES `seeding`.`Customers` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
